# Generated by Django 6.0.2 on 2026-04-28 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0011_alter_workshift_options_workshift_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(verbose_name='الشهر')),
                ('year', models.PositiveIntegerField(verbose_name='السنة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('approved', 'معتمد'), ('paid', 'مدفوع')], default='draft', max_length=20, verbose_name='الحالة')),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الرواتب')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الخصومات')),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='صافي الرواتب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الصرف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payrolls', to=settings.AUTH_USER_MODEL, verbose_name='اعتمده')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
            ],
            options={
                'verbose_name': 'مسير رواتب',
                'verbose_name_plural': 'مسيرات الرواتب',
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('late', 'متأخر'), ('excused', 'إذن'), ('holiday', 'إجازة')], default='present', max_length=20, verbose_name='الحالة')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='وقت الحضور')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='وقت الانصراف')),
                ('late_minutes', models.PositiveIntegerField(default=0, verbose_name='دقائق التأخير')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='inventory.employee', verbose_name='الموظف')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='سجّل بواسطة')),
            ],
            options={
                'verbose_name': 'سجل حضور',
                'verbose_name_plural': 'سجلات الحضور',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SalarySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الراتب الأساسي')),
                ('incentives', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الحوافز')),
                ('advances', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السلف')),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خصومات أخرى')),
                ('absent_days', models.PositiveIntegerField(default=0, verbose_name='أيام الغياب')),
                ('late_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خصم التأخير')),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='صافي الراتب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_paid', models.BooleanField(default=False, verbose_name='مدفوع؟')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_slips', to='inventory.employee', verbose_name='الموظف')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slips', to='hr.payrollrun', verbose_name='مسير الراتب')),
            ],
            options={
                'verbose_name': 'قسيمة راتب',
                'verbose_name_plural': 'قسائم الرواتب',
                'ordering': ['employee__name'],
                'unique_together': {('payroll_run', 'employee')},
            },
        ),
    ]
