# Generated by Django 6.0.2 on 2026-05-17 16:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CASH', 'خزينة نقدية'), ('BANK', 'حساب بنكي'), ('VODAFONE', 'فودافون كاش'), ('INSTAPAY', 'إنستاباي'), ('CARD', 'بطاقة بنكية')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'حساب خزينة',
                'verbose_name_plural': 'حسابات الخزينة',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TreasuryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'دخل'), ('EXPENSE', 'خرج'), ('ADJUSTMENT', 'تسوية')], max_length=20)),
                ('category', models.CharField(choices=[('SALE', 'مبيعات'), ('PURCHASE', 'مشتريات'), ('SALARY', 'رواتب'), ('INSTALLMENT', 'قسط'), ('RENT', 'إيجار'), ('ELECTRICITY', 'كهرباء'), ('MAINTENANCE', 'صيانة'), ('MANUAL', 'إدخال يدوي'), ('OTHER', 'أخرى')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_auto', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='treasury.treasuryaccount', verbose_name='الحساب')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'حركة خزينة',
                'verbose_name_plural': 'حركات الخزينة',
                'ordering': ['-created_at'],
            },
        ),
    ]
