[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python smart_erp_backend/manage.py migrate --noinput && python smart_erp_backend/manage.py collectstatic --noinput && gunicorn core.wsgi:application --chdir smart_erp_backend --bind 0.0.0.0:$PORT --workers 2"
healthcheckPath = "/api/login/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
