# Generated by Django 6.0.2 on 2026-02-27 06:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installment',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المتبقي'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='installment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='إجمالي مبلغ القسط'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='هل تم السداد؟'),
        ),
    ]
