# Generated by Django 6.0.2 on 2026-02-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_installment_created_at_installment_remaining_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الموظف')),
                ('position', models.CharField(max_length=100, verbose_name='المسمى الوظيفي')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الراتب الأساسي')),
                ('advances', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السلف')),
                ('incentives', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الحوافز')),
                ('attendance', models.CharField(default='present', max_length=20, verbose_name='الحضور')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('rent', 'إيجار'), ('electricity', 'كهرباء'), ('maintenance', 'صيانة'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='الفئة'),
        ),
        migrations.AddField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
    ]
