# Generated by Django 6.0.2 on 2026-02-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_employee_expense_category_expense_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='base_salary',
            new_name='baseSalary',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='title',
            new_name='type',
        ),
        migrations.AddField(
            model_name='installment',
            name='installments_count',
            field=models.IntegerField(default=1, verbose_name='عدد الأقساط'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ'),
        ),
    ]
