# Generated by Django 6.0.2 on 2026-03-15 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_base_salary_employee_basesalary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('مدير', 'مدير النظام'), ('كاشير', 'كاشير')], default='كاشير', max_length=20, verbose_name='الوظيفة')),
                ('permissions', models.JSONField(blank=True, default=dict, verbose_name='الصلاحيات')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
