# Generated by Django 6.0.2 on 2026-04-15 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
