# Generated by Django 6.0.2 on 2026-04-15 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.workshift'),
        ),
    ]
