# Generated by Django 6.0.2 on 2026-04-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Smart ERP', max_length=200, verbose_name='اسم المتجر')),
                ('store_logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='شعار المتجر')),
                ('currency', models.CharField(default='EGP', max_length=10, verbose_name='العملة')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=14.0, max_digits=5, verbose_name='نسبة الضريبة')),
                ('primary_color', models.CharField(default='#3B82F6', max_length=7, verbose_name='اللون الأساسي')),
                ('system_name', models.CharField(default='Smart ERP', max_length=100, verbose_name='اسم النظام')),
                ('is_configured', models.BooleanField(default=False, verbose_name='تم الإعداد')),
            ],
            options={
                'verbose_name': 'إعدادات المتجر',
                'verbose_name_plural': 'إعدادات المتجر',
            },
        ),
    ]
