# Generated by Django 6.0.2 on 2026-04-16 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_invoice_discount_amount_invoice_tax_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المندوب')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('target_sales', models.DecimalField(decimal_places=2, default=100000, max_digits=12, verbose_name='المبيعات المستهدفة')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=3.0, max_digits=5, verbose_name='نسبة العمولة (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='التصنيف'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='صورة المنتج'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='inventory.salesrepresentative'),
        ),
    ]
