# Generated by Django 6.0.2 on 2026-04-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_sale_saleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ الضريبة'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product_name',
            field=models.CharField(default='', help_text='اسم المنتج وقت البيع (لا يتغير حتى لو تغير اسم المنتج لاحقاً)', max_length=255, verbose_name='اسم المنتج (Snapshot)'),
        ),
    ]
