# Generated by Django 6.0.2 on 2026-04-28 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_sale_tax_amount_saleitem_product_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshift',
            options={'ordering': ['-start_time'], 'verbose_name': 'وردية', 'verbose_name_plural': 'الورديات'},
        ),
        migrations.AddField(
            model_name='workshift',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='workshift',
            name='difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الفرق'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='expected_cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الكاش المتوقع'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='shift_date',
            field=models.DateField(default='2024-01-01', verbose_name='تاريخ الوردية'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='status',
            field=models.CharField(choices=[('open', 'مفتوحة'), ('closed', 'مغلقة')], default='open', max_length=10, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي المبيعات'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='actual_cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الكاش الفعلي'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت النهاية'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='وقت البداية'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='starting_cash',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='رصيد أول الوردية'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
