# Generated by Django 6.0.2 on 2026-04-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='date_format',
            field=models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='DD/MM/YYYY', max_length=20, verbose_name='تنسيق التاريخ'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='invoice_due_days',
            field=models.IntegerField(default=30, verbose_name='أيام استحقاق الفاتورة'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='invoice_notes',
            field=models.TextField(blank=True, default='', verbose_name='ملاحظات ثابتة في الفاتورة'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='invoice_prefix',
            field=models.CharField(default='INV', max_length=10, verbose_name='بادئة الفاتورة'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='invoice_starting_number',
            field=models.IntegerField(default=1, verbose_name='رقم بداية الفواتير'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='language',
            field=models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=10, verbose_name='اللغة'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='lockout_duration_minutes',
            field=models.IntegerField(default=30, verbose_name='مدة الحظر بالدقائق'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='max_login_attempts',
            field=models.IntegerField(default=5, verbose_name='محاولات الدخول المسموحة'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='session_timeout_hours',
            field=models.IntegerField(default=8, verbose_name='مدة الجلسة بالساعات'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='show_tax_on_invoice',
            field=models.BooleanField(default=True, verbose_name='إظهار الضريبة في الفاتورة'),
        ),
    ]
