# Generated by Django 6.0.2 on 2026-04-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_storesettings_address_storesettings_date_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'كاش'), ('vodafone_cash', 'فودافون كاش'), ('instapay', 'انستاباي'), ('card', 'بطاقة بنكية'), ('credit', 'آجل')], default='cash', max_length=20, verbose_name='طريقة الدفع'),
        ),
    ]
