# Generated by Django 6.0.2 on 2026-05-01 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_product_barcode_alter_product_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installment',
            options={'verbose_name': 'قسط', 'verbose_name_plural': 'الأقساط'},
        ),
        migrations.RemoveField(
            model_name='installment',
            name='installments_count',
        ),
        migrations.RemoveField(
            model_name='installment',
            name='invoice',
        ),
        migrations.AddField(
            model_name='installment',
            name='down_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المقدم'),
        ),
        migrations.AddField(
            model_name='installment',
            name='months_count',
            field=models.IntegerField(default=1, verbose_name='عدد الأشهر'),
        ),
        migrations.AddField(
            model_name='installment',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='inventory.sale', verbose_name='فاتورة البيع'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='إجمالي مبلغ التقسيط'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='due_date',
            field=models.DateField(verbose_name='تاريخ أول قسط'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='هل تم السداد الكامل؟'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'كاش'), ('vodafone_cash', 'فودافون كاش'), ('instapay', 'انستاباي'), ('card', 'بطاقة بنكية'), ('credit', 'آجل'), ('installment', 'تقسيط')], default='cash', max_length=20, verbose_name='طريقة الدفع'),
        ),
    ]
