# Generated by Django 6.0.2 on 2026-05-11 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_supplier_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_rating', models.PositiveSmallIntegerField(default=3, verbose_name='تقييم الاستلام')),
                ('quality_rating', models.PositiveSmallIntegerField(default=3, verbose_name='تقييم الجودة')),
                ('price_rating', models.PositiveSmallIntegerField(default=3, verbose_name='تقييم السعر')),
                ('communication_rating', models.PositiveSmallIntegerField(default=3, verbose_name='تقييم التواصل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='inventory.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'تقييم المورد',
                'verbose_name_plural': 'تقييمات الموردين',
                'ordering': ['-created_at'],
            },
        ),
    ]
