# Generated by Django 6.0.2 on 2026-05-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_supplierevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierevaluation',
            name='goods_image',
            field=models.ImageField(blank=True, null=True, upload_to='supplier_evaluations/', verbose_name='صورة البضاعة'),
        ),
        migrations.AddField(
            model_name='supplierevaluation',
            name='invoice_image',
            field=models.ImageField(blank=True, null=True, upload_to='supplier_evaluations/', verbose_name='صورة الفاتورة'),
        ),
    ]
