# Generated by Django 6.0.2 on 2026-05-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_supplierevaluation_goods_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الرصيد الافتتاحي'),
        ),
    ]
