# Generated by Django 6.0.2 on 2026-05-20 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_add_opening_balance_to_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='cost_price_at_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تكلفة الوحدة وقت البيع'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='تاريخ المصروف'),
        ),
    ]
