# Generated by Django 6.0.2 on 2026-05-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_add_cost_price_at_sale_and_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='treasury_alert_threshold',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=12, verbose_name='حد تنبيه الخزينة المنخفضة'),
        ),
    ]
