# Generated by Django 6.0.2 on 2026-05-20 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial_rbac_models'),
        ('inventory', '0023_add_treasury_alert_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='accounts.role', verbose_name='الدور (جديد)'),
        ),
    ]
