# Generated by Django 6.0.2 on 2026-05-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_add_role_fk_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='محظور حتى'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='login_attempts',
            field=models.IntegerField(default=0, verbose_name='محاولات الدخول الفاشلة'),
        ),
    ]
