# Generated by Django 6.0.2 on 2026-05-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_add_login_attempts_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='credit_markup_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة زيادة سعر الآجل %'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='installment_markup_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة زيادة سعر التقسيط %'),
        ),
    ]
