# Generated by Django 6.0.2 on 2026-06-09 14:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_add_discount_type_to_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='down_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='المقدم'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='months_count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد الأشهر'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='المبلغ المتبقي'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='قيمة الخصم'),
        ),
    ]
