# Generated by Django 6.0.2 on 2026-06-20 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_add_enable_tax_to_storesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProductRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='متوسط سعر التكلفة')),
                ('avg_quality', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='متوسط تقييم الجودة')),
                ('avg_delivery', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='متوسط تقييم الاستلام')),
                ('total_purchases', models.PositiveIntegerField(default=0, verbose_name='عدد المشتريات')),
                ('last_purchase_date', models.DateField(blank=True, null=True, verbose_name='تاريخ آخر عملية شراء')),
                ('rank', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('recommendation_reason', models.TextField(blank=True, verbose_name='سبب التوصية')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_rankings', to='inventory.product', verbose_name='المنتج')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_rankings', to='inventory.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'ترتيب المورد للمنتج',
                'verbose_name_plural': 'ترتيبات الموردين للمنتجات',
                'ordering': ['product', 'rank'],
                'unique_together': {('product', 'supplier')},
            },
        ),
    ]
