# Generated by Django 6.0.2 on 2026-02-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='اسم المؤسسة')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('commercial_register', models.CharField(max_length=100, verbose_name='السجل التجاري')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='system_logos/')),
                ('enable_inventory', models.BooleanField(default=True)),
                ('enable_sales', models.BooleanField(default=True)),
                ('enable_employees', models.BooleanField(default=True)),
                ('enable_installments', models.BooleanField(default=True)),
            ],
        ),
    ]
