# Generated by Django 6.0.2 on 2026-04-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Smart ERP System', max_length=255, verbose_name='اسم الشركة')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='شعار الشركة')),
                ('company_address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم الضريبي')),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=14.0, max_digits=5, verbose_name='نسبة الضريبة VAT (%)')),
                ('currency', models.CharField(default='ج.م', max_length=20, verbose_name='العملة الأساسية')),
                ('payroll_tax_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='ضريبة الرواتب (%)')),
                ('max_advance_limit', models.DecimalField(decimal_places=2, default=2000.0, max_digits=10, verbose_name='سقف السلف الشهرية (ج.م)')),
                ('allow_negative_stock', models.BooleanField(default=False, verbose_name='السماح بالبيع بالسالب')),
                ('auto_update_retail_price', models.BooleanField(default=True, verbose_name='تحديث السعر التلقائي عند الشراء')),
                ('low_stock_threshold', models.DecimalField(decimal_places=2, default=5.0, max_digits=10, verbose_name='حد التنبيه للنواقص')),
                ('work_start_time', models.TimeField(default='09:00:00', verbose_name='بداية ساعات العمل')),
                ('work_end_time', models.TimeField(default='23:00:00', verbose_name='نهاية ساعات العمل')),
                ('max_cashier_discount', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='سقف خصم الكاشير المسموح (%)')),
                ('token_expiry_days', models.IntegerField(default=7, verbose_name='مدة صلاحية الجلسة (أيام)')),
                ('primary_color', models.CharField(default='#3B82F6', max_length=10, verbose_name='اللون الأساسي (Hex)')),
                ('print_logo_on_invoice', models.BooleanField(default=True, verbose_name='إظهار اللوجو في الفاتورة')),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
    ]
