# Generated by Django 6.0.2 on 2026-02-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='enable_accounts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='enable_ai_assistant',
            field=models.BooleanField(default=True),
        ),
    ]
