# Generated by Django 6.0.2 on 2026-02-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0002_systemconfiguration_enable_accounts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='enable_installments',
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='enable_automation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='enable_accounts',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='enable_ai_assistant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='enable_employees',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='enable_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='enable_sales',
            field=models.BooleanField(default=False),
        ),
    ]
