# Generated by Django 6.0.2 on 2026-02-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0003_remove_systemconfiguration_enable_installments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfiguration',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='commercial_register',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='السجل التجاري'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المؤسسة'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
    ]
