# Generated by Django 6.0.2 on 2026-03-02 21:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0004_alter_systemconfiguration_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfiguration',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='اسم المؤسسة يجب أن يحتوي على حروف فقط (لا يسمح بالأرقام).', regex='^[a-zA-Z\\s\\u0600-\\u06FF]+$')], verbose_name='اسم المؤسسة'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يكون أرقاماً فقط (من 9 لـ 15 رقم).', regex='^\\+?1?\\d{9,15}$')], verbose_name='رقم الهاتف'),
        ),
    ]
