# Generated by Django 6.0.2 on 2026-02-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم العميل')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم التليفون')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الرصيد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
