# Generated by Django 6.0.2 on 2026-02-27 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_installment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Installment',
        ),
    ]
