# Generated by Django 6.0.2 on 2026-05-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رقم التليفون'),
        ),
    ]
