# Generated by Django 6.0.2 on 2026-03-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
