# Generated by Django 6.0.2 on 2026-02-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='product',
            name='half_wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر نصف الجملة'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='available', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المورد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_stock',
            field=models.IntegerField(default=0, verbose_name='الكمية الحالية'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock_level',
            field=models.IntegerField(default=5, verbose_name='حد التنبيه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر الجملة'),
            preserve_default=False,
        ),
    ]
