# Generated by Django 6.0.2 on 2026-02-28 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0004_remove_invoice_customer_remove_installment_invoice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الفاتورة')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الإجمالي')),
                ('payment_method', models.CharField(choices=[('CASH', 'نقدي'), ('CREDIT', 'آجل'), ('INSTALLMENT', 'تقسيط')], default='CASH', max_length=20, verbose_name='طريقة الدفع')),
                ('is_anomaly', models.BooleanField(default=False, verbose_name='فاتورة مشبوهة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer', verbose_name='العميل')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='إجمالي الصنف')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='المنتج')),
            ],
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='وقت البدء')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإغلاق')),
                ('is_open', models.BooleanField(default=True, verbose_name='هل الوردية مفتوحة؟')),
                ('starting_cash', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الرصيد الافتتاحي')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.workshift', verbose_name='الوردية'),
        ),
    ]
