# Generated by Django 6.0.2 on 2026-03-02 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.workshift', verbose_name='الوردية'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي الصنف'),
        ),
    ]
