# Generated by Django 6.0.2 on 2026-03-03 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0002_alter_invoice_shift_alter_invoiceitem_line_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='إجمالي مبلغ التقسيط')),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المقدم المدفوع')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المتبقي')),
                ('installments_count', models.PositiveIntegerField(verbose_name='عدد الأقساط')),
                ('start_date', models.DateField(verbose_name='تاريخ أول قسط')),
                ('is_completed', models.BooleanField(default=False, verbose_name='هل اكتمل السداد؟')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='العميل')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plan', to='sales.invoice', verbose_name='الفاتورة')),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ القسط')),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('PAID', 'تم الدفع'), ('LATE', 'متأخر')], default='PENDING', max_length=20, verbose_name='حالة القسط')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدفع الفعلي')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='sales.installmentplan', verbose_name='خطة التقسيط')),
            ],
        ),
    ]
