# Generated by Django 6.0.2 on 2026-05-20 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='اسم الدور')),
                ('name_en', models.CharField(blank=True, max_length=50, verbose_name='الاسم بالإنجليزية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('level', models.IntegerField(default=99, help_text='0 = أعلى صلاحية (مدير)، الأرقام الأكبر = صلاحية أقل', verbose_name='المستوى')),
                ('is_system', models.BooleanField(default=False, help_text='يحمي الأدوار المدمجة من الحذف', verbose_name='دور نظام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'دور',
                'verbose_name_plural': 'الأدوار',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(help_text="مثال: 'sales', 'inventory', 'reports'", max_length=50, verbose_name='الموديول')),
                ('action', models.CharField(help_text="مثال: 'view', 'create', 'edit', 'delete', 'export'", max_length=50, verbose_name='الإجراء')),
                ('description_ar', models.CharField(max_length=200, verbose_name='الوصف بالعربية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'صلاحية',
                'verbose_name_plural': 'الصلاحيات',
                'ordering': ['module', 'action'],
                'unique_together': {('module', 'action')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.permission', verbose_name='الصلاحية')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.role', verbose_name='الدور')),
            ],
            options={
                'verbose_name': 'صلاحية الدور',
                'verbose_name_plural': 'صلاحيات الأدوار',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted', models.BooleanField(default=True, help_text='True = منح، False = منع صريح', verbose_name='ممنوحة')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='accounts.permission', verbose_name='الصلاحية')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions_rbac', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'صلاحية المستخدم',
                'verbose_name_plural': 'صلاحيات المستخدمين',
                'unique_together': {('user', 'permission')},
            },
        ),
    ]
