# Generated by Django 6.0.2 on 2026-04-16 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الموظف احتياطي')),
                ('operation_type', models.CharField(max_length=100, verbose_name='نوع العملية')),
                ('old_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='القيمة القديمة')),
                ('new_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='القيمة الجديدة')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('severity', models.CharField(choices=[('high', 'خطر عالي'), ('medium', 'خطر متوسط'), ('low', 'خطر منخفض')], default='medium', max_length=20, verbose_name='الخطورة')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='وقت العملية')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'عملية مشبوهة',
                'verbose_name_plural': 'عمليات مشبوهة',
                'ordering': ['-timestamp'],
            },
        ),
    ]
